### ISSUE TITLE
[Feature Request] For public views - force dark theme

### ISSUE THREAD

**Issue by itsnedkeren** [ppfeufer/aa-intel-tool#113]
### Context

In which context would you expect your suggested feature to be useful?

Using a dark theme, is easier on the eyes. For public views, no theme seems to be selectable.

### Describe the feature you have in mind

Default the app to use the dark theme for all users.
Logged in users can change per the theme selector
Public view users are forced to use the dark theme

### Additional context

Add any other context or screenshots/mockups about the feature request here.

**Comment by ppfeufer** [comment]
Apps should not force any theme.

Theme selection in public views would be an AA feature.

Hint:
You can set a default theme already in your `local.py` …
