### ISSUE TITLE
[BUG] Ship with cosmic sig-like name makes parsing fail

### ISSUE THREAD

**Issue by Maestro-Zacht** [ppfeufer/aa-intel-tool#82]
### Bug Description

Example of copied string:
`17736    WWV-984    Cosmic Signa    Nightmare    3,142 m`
Error:
`The provided data could not be parsed. (A parser error occurred » No suitable parser found. Input is not a supported intel type or malformed …)`

### Steps to Reproduce

1. Paste the above string in the intel tool

### Expected behavior

Run fine

### Please complete the following information:

- App Version: 2.0.0
- Alliance Auth Version: 4.0.1
- Browser and Version: Chrome 123.0.6312.124

**Comment by Maestro-Zacht** [comment]
Some of my mates have this error instead:
`(System Error) Something unexpected happened. (invalid literal for int() with base 10: '')`

**Comment by ppfeufer** [comment]
I need the exact string as copied from the ingame d-scan window.

The string you posted is not a valid d-scan entry.
In a d-scan, the elements are separated by tabs, not spaces (as in your example).

Example:
```plain
601	WWV-984    Cosmic Signa	Ibis	1,475 km
```

Can be parsed
![image](https://github.com/ppfeufer/aa-intel-tool/assets/2989985/24a577a4-63a4-4601-84c1-40d923c77f61)

**Comment by ppfeufer** [comment]
And as you can see here, your string has spaces and no tabs at all, so the parser is probably trying to parse this as a character name

![image](https://github.com/ppfeufer/aa-intel-tool/assets/2989985/e1747dc3-e2e4-4d66-a4b1-96a4f7a4c72a)

**Comment by ppfeufer** [comment]
> Some of my mates have this error instead: `(System Error) Something unexpected happened. (invalid literal for int() with base 10: '')`

What did he post?

**Comment by Maestro-Zacht** [comment]
The same ship, I'll try to replicate it

**Comment by Maestro-Zacht** [comment]
Correct steps to reproduce:

1. Copy an unscanned cosmic signature from probe window
2. Paste it as your ship name
3. Copy dscan from another client
4. paste in intel tool

Error: `(System Error) Something unexpected happened. (invalid literal for int() with base 10: '')`
String: `17736	RWV-449	Cosmic Signa	Nightmare	14 km`
