### ISSUE TITLE
[Feature Request] Add CORP/Alliance logo to public view

### ISSUE THREAD

**Issue by itsnedkeren** [ppfeufer/aa-intel-tool#91]
### Context

In which context would you expect your suggested feature to be useful?

Just for recognition I guess.

### Describe the feature you have in mind

It would be nice to add the corp/alliance logo of AA to the public view page of the Intel Tool.

### Additional context

I have added a screenshot here with suggestions of the logo placement. But please do as you see fit to make it work.

https://i.imgur.com/eoDy4qH.png

**Comment by ppfeufer** [comment]
You might want to update your Auth …

![image](https://github.com/ppfeufer/aa-intel-tool/assets/2989985/0df14769-cf4f-4bf1-a42e-10e499623d40)

**Comment by itsnedkeren** [comment]
Weird. I'm at latest 4.0.1 and Intel 2.1.0. Will check why it's not there. Thanks and sorry for the inconvenience.
